import Head from 'next/head'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Ul from '../components/ul'
import React from 'react'
import Banner from '../components/banner'
import styles from '../styles/about.module.css'
import Prefooter from '../components/prefooter'

export default function Aboutus() {
    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <div className={ styles.aboutcont }>
                <div className={ styles.first }>
                    <h1>About DAMAN</h1>
                    <p>
                        <b>Happiness..</b> When His Highness Sheikh Mohammed bin Rashid Al Maktoum, Vice President,
                        Prime Minister and the ruler of Dubai launched the Happiness Agenda, we knew with absolute certainty
                        that we would be an integral part of this step that is expected to result in numerous
                        changes and lead to the enhancement of many sectors. Since this agenda aims to bring
                        happiness to people, it will in turn encourage creativity and reduce many of the burdens
                        that hinder progress and development not only on the individual and social level,
                        but the nation as a whole.
                    </p>
                </div>
                <div className={ styles.snd }>
                    <ul>
                        <li>Provide the foundations for major companies and projects.</li>
                        <li>Draw up long-term strategic plans.</li>
                        <li>identify an approach and an integrated system by our experts
                            to ensure the ability to compete.</li>
                        <li>Carry out all government interactions and handle the necessary paperwork.</li>
                    </ul>
                    <img src='2.jpg' alt='future development' />
                </div>

                <div className={ styles.first }>
                    <p>
                        Therefore, our Daman is here to contribute to that by way of introducing
                        a variety of services and innovative solutions that make life easier and
                        create an environment conducive for the success and development of both
                        large and emerging companies. These services also extend to individuals
                        and pave the way for them to raise their productive potential and overcome
                        obstacles related to residency permits, ID cards, and so on. On that account,
                        we are proud to be playing a role in the spreading of happiness through our
                        dedicated teams who work tirelessly to serve you, wherever you are.
                    </p>
                    <hr style={ { width: '80%' } } />
                </div>
                <div className={ styles.thrd }>
                    <h1>Our Core Values</h1>
                    <div className={ styles.subthrd }>
                        <p>&#9733; Committed to delivering the best.</p>
                        <p>&#9733; We care for your business just like ours.</p>
                    </div>
                    <div className={ styles.subthrd }>
                        <p>&#9733; Honest and transparent services. </p>
                        <p>&#9733; Keep learning and adapting to new technologies. </p>
                    </div>
                </div>
            </div>
        </>
    )
}
