import Head from 'next/head'
import React from 'react'
import Footer from '../components/footer'
import Layout from '../components/layout'
import Navbar from '../components/navbar'
import Ul from '../components/ul'
import Banner from '../components/banner'
import styles from '../styles/home.module.css'
import Prefooter from '../components/prefooter'

export default function Home() {
  return (
    <>
      <Head>
        <title>Daman Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.png" />
      </Head>
      <div className={ styles.whyuscont }>
        <h1> Hire Us For</h1>
        <div className={ styles.whyus }>
          <div className={ styles.telt }>
            <h1>1- Security Clearances</h1>
            <img src='security.jpg' alt='Security clearances' />
            <p>With our qualified team, we help you in all transactions to extract the security clearances.</p>
          </div>
          <div className={ styles.telt }>
            <h1>2- Establishing A Facility</h1>
            <img src='facility.jpg' alt='Facility establishing' />
            <p>Within this step, the required documents shall be signed in order to complete the transaction for the country.</p>
          </div>
          <div className={ styles.telt }>
            <h1>3- Residence</h1>
            <img src='residence.jpg' alt='residence visa extracting' />
            <p>With the help of our team, we speed up the process of extracting the required residence and visas.</p>
          </div>
        </div>
        <hr style={ { width: '80%' } } />
      </div>


      <div className={ styles.idea }>
        <img src='idea.jpg' alt='Motivational Business Quote' />
        <p>
          <b>“</b>It Takes An Idea, Faith And Immense Amount Of Hard Working...
          But, Eventually, Dreams Come True.<b>”</b>
        </p>
      </div>


      <div className={ styles.vismis }>
        <div className={ styles.nos }>
          <img src='light.png' alt='' />
          <h1>Our Vision</h1>
          <p>We don’t climb up to Daman, we make it.
            Our community of investors, elder statesmen, public figures and businessmen
            are in need of an integrated system and an unparalleled service.
            So we made our own summit by tending to their every need in order to smoothen the path
            towards a steadier and brighter future where great success awaits.
            Our vision does not only apply to our beloved country, United Arab Emirates, but extends to the Arabic world.
            Thus, we strive to realize our global vision of achieving unprecedented growth in serving the business
            and investment sectors.
          </p>
        </div>
        <div className={ styles.nos }>
          <img src='target.png' alt='' />
          <h1>Our Mission</h1>
          <p>The mission of our Daman is to excel despite the short time window
            to accomplish the tasks entrusted to us with the highest levels of efficiency
            with an emphasis on maintaining our credibility and ensuring the utmost transparency
            all for your comfort and fulfilling your expectations so as to achieve your satisfaction and approval.
            Our mission is to help you realize your dreams on the ground, and to rise up with what we put on the ground
            to head to the clouds, and to preserve that forever.
            Our mission is for you to close your eyes and open them to innovative solutions
            for your problems and a paved road to your success, free of obstacles.
          </p>
        </div>
      </div>
      <hr style={ { width: '80%' } } />


      <div className={ styles.advcont }>
        <h1>Why Choose Us Exactly?</h1>
        <div className={ styles.adv }>
          <p> We are the right term for your business.
            We have the expertise and knowledge to offer impartial advice and services at an honest price.
            With us you’ll feel heard. We listen to our client requirements and then select the right solution that fits.
            We care for your business as our own.
            We take a sincere interest in it and genuinely want to help your company reach its potential.
          </p>
          <div className={ styles.advgrid }>
            <div><img src='star.png' alt='' /> <p>Expertise</p></div>
            <div><img src='dollar.png' alt='' /><p>Price</p></div>
            <div><img src='ear.png' alt='' /><p>Communication</p></div>
            <div><img src='hand.png' alt='' /><p>Co-operation</p></div>
          </div>
        </div>
        <hr style={ { width: '80%' } } />
      </div>


      <div className={ styles.clientscont }>
        <h1> Clients We&apos;ve Worked With</h1>
        <div className={ styles.clients }>
          <img src='star.png' alt='' />
          <img src='star.png' alt='' />
          <img src='star.png' alt='' />
          <img src='star.png' alt='' />
        </div>
      </div>
    </>
  )
}
