import Head from 'next/head'
import React from 'react'
import Navbar from '../components/navbar'
import Ul from '../components/ul'
import Banner from '../components/banner'
import styles from '../styles/services.module.css'
import Prefooter from '../components/prefooter'
import Footer from '../components/footer'
export default function Services() {
    return (
        <>
            <Head>
                <title>Daman Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <div className={ styles.servcont }>
                <h1> How Can We Help You?</h1>
                <div className={ styles.serv }>
                    <div className={ styles.telt }>
                        <h1>CO. REGISTRATION IN UAE.</h1>
                        <ul>
                            <li>Residence permit in Dubai.</li>
                            <li>Unlimited number of visas.</li>
                            <li>More business activities available for licensing.</li>
                            <li>100% Own of your business ,100% tax exemption.</li>
                            <li>Trade in the GCC ,Open bank accounts</li>
                        </ul>
                    </div>
                    <div className={ styles.telt }>
                        <h1>BUSINESS STARTUP IN THE FREE ZONE.</h1>
                        <ul>
                            <li>No foreign ownership</li>
                            <li>Zero income tax ,Zero corporate tax.</li>
                            <li>No export tax ,No restriction on currency and repatriation of funds.</li>
                            <li>No restriction on hiring foreign employees.</li>
                            <li>Trade in the GCC ,Open bank accounts.</li>
                        </ul>
                    </div>
                    <div className={ styles.telt }>
                        <h1>OFFSHORE COMPANIES.</h1>
                        <ul>
                            <li>Providing a gateway for international market expansion.</li>
                            <li>Access to a stable and business-friendly legal system.</li>
                            <li>Offering better access to global funding.</li>
                            <li>Access to a more flexible regulatory regime.</li>
                            <li>Offering tax neutrality on international earnings in respect of (depending on jurisdiction) personal or company income, capital gains and inheritance taxes.</li>
                        </ul>
                    </div>
                </div>
            </div>
            <hr style={ { width: '80%' } } />

            <div className={ styles.clientscont }>
                <h1> Clients We&apos;ve Worked With</h1>
                <div className={ styles.clients }>
                    <img src='star.png' alt='' />
                    <img src='star.png' alt='' />
                    <img src='star.png' alt='' />
                    <img src='star.png' alt='' />
                </div>
            </div>
        </>
    )
}
